name: Lint

on:
  workflow_dispatch:

  workflow_call:

  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Project
        uses: $/.github/actions/setup-project
      - run: npm run lint:eslint

  astro:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Project
        uses: $/.github/actions/setup-project
      - run: npm run lint:astro

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Project
        uses: $/.github/actions/setup-project
      - run: npm run lint:prettier
